apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: aceosccm6-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:6dcdb09af1f68f22edbbd06df7457b865b3032d1@sha256:4d4bb91ecfc40d44936ec7db847f8bb50b877e90d139cee8d4f82b47e17505f7
          name: container-image
